language: ruby
cache: bundler
rvm:
  - ruby-head
before_script:
  - pip install --user -r requirements.txt
script:
  - behave tests/before_build
  - bundle exec jekyll build
  - behave tests/after_build
deploy:
  provider: pages
  skip_cleanup: false
  github_token: $GITHUB_TOKEN
  target_branch: gh-pages
  on:
    branch: master