collections:
  hg_events:
    output: false

webrick:
  headers:
    Access-Control-Allow-Origin: '*'

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - tests
  - requirements.txt
  - vendor
